# helm install kafka bitnami/kafka -f  https://raw.githubusercontent.com/phucng2017/k8s/refs/heads/main/k8s-helm-kafka/values_v6.yaml

replicaCount: 3
persistence:
  enabled: true
  size: 20Gi
zookeeper:
  replicaCount: 3
  persistence:
    enabled: true
    size: 10Gi
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
auth:
  clientProtocol: SASL_PLAINTEXT  # Sử dụng SASL_PLAINTEXT cho client
  interBrokerProtocol: SASL_PLAINTEXT  # Sử dụng SASL_PLAINTEXT giữa các brokers
  jaas:
    clientUsers:  # Danh sách users và passwords cho client
      - username: user1
        password: "9ZxnKEDFiM"
    interBrokerUser: admin  # User và password cho giao tiếp giữa các brokers
    interBrokerPassword: "admin-password"


# replicaCount: 3
# persistence:
#   enabled: true
#   size: 20Gi
# zookeeper:
#   replicaCount: 3
#   persistence:
#     enabled: true
#     size: 10Gi
# resources:
#   requests:
#     memory: "512Mi"
#     cpu: "500m"
#   limits:
#     memory: "1Gi"
#     cpu: "1"
# auth:
#   clientProtocol: sasl
#   interBrokerProtocol: sasl
#   jaas:
#     clientUser: user1
#     clientPassword: "9ZxnKEDFiM"
#     interBrokerUser: admin
#     interBrokerPassword: "admin-password"