#Link
#https://artifacthub.io/packages/helm/bitnami/redis

#TRIEN KHAI:
#helm install redis bitnami/redis -f https://raw.githubusercontent.com/phucng2017/k8s/refs/heads/main/5-k8s-helm-redis/values_v8.yaml  --namespace cache

#UNINSTALL
#helm uninstall my-redis

#==================================================
# values_v7.yaml


auth:
  password: "mysecretpassword"

global:
  redis:
    password: "mysecretpassword" # Mật khẩu cho Redis (bạn có thể chỉnh sửa)
    
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.4.2-debian-12-r0
  digest: ""
  ## Specify a imagePullPolicy
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Enable debug mode
  ##
  debug: false

master:
  service:
    type: NodePort         # Chọn loại Service là NodePort
    ports:
      redis: 6379
    # nodePort: 30001        # Port mà Redis master sẽ expose
    nodePorts:
      redis: "30007"
  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
    
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"


# service:
#   type: NodePort                # Loại service là NodePort
#   # port: 6379                    # Cổng service Redis
#   # nodePort: 30000
#   ports:
#     redis: 6379
#   nodePorts:
#       redis: "300000"


