ports:
  traefik:
    expose: true
    port: 9000
    nodePort: 31000
    protocol: TCP
  web:
    expose: true
    port: 80
    nodePort: 32000
    protocol: TCP
  websecure:
    expose: true
    port: 443
    nodePort: 32443
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"  # Lưu ý: Chỉ bật trong môi trường dev/test
  - "--entrypoints.traefik.address=:9000"