
#TRIEN KHAI:
#helm install my-redis bitnami/redis -f https://raw.githubusercontent.com/phucng2017/k8s/refs/heads/main/k8s-helm-redis/values.yaml


# custom-values.yaml
auth:
  password: "mysecretpassword"

global:
  redis:
    password: "mysecretpassword" # Mật khẩu cho Redis (bạn có thể chỉnh sửa)

master:
  service:
    type: NodePort         # Chọn loại Service là NodePort
    ports:
      redis: 6379
    # nodePort: 30001        # Port mà Redis master sẽ expose
    nodePorts:
      redis: "30001"
  persistence:
    enabled: true
    size: 1Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# service:
#   type: NodePort                # Loại service là NodePort
#   # port: 6379                    # Cổng service Redis
#   # nodePort: 30000
#   ports:
#     redis: 6379
#   nodePorts:
#       redis: "300000"


