# https://github.com/redpanda-data/console?tab=readme-ov-file

# vi values-redpanda-v2.yaml
#(voi noi dung ben duoi)
# kubectl apply -f values-redpanda-v2.yaml 
# kubectl delete -f values-redpanda-v2.yaml 

# PORT: 30006

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: kafka
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: docker.redpanda.com/redpandadata/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              # value: "192.168.64.18:30521"
              value: "kafka.kafka.svc.cluster.local:9092"              
            - name: KAFKA_TLS_ENABLED
              value: "false"                # Tắt TLS
            - name: KAFKA_SASL_ENABLED
              value: "true"                 # Bật SASL
            - name: KAFKA_SASL_USERNAME
              value: "user1"                # Tên người dùng SASL
            - name: KAFKA_SASL_PASSWORD
              value: "ioyWIoVAvb"           # Mật khẩu SASL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: kafka
  labels:
    app: redpanda-console
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    app: redpanda-console
  type: NodePort  # Loại service là NodePort để truy cập từ bên ngoài