logs:
  enabled: true
  configs:
    - name: kubernetes-logs
      positions:
        directory: /tmp/positions
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods
          pipeline_stages:
            - docker: {}
            - json: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container

# backend:
#   type: loki
#   loki:
#     host: "http://loki:3100/loki/api/v1/push"

# input:
#   kubernetes:
#     enabled: true